apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
      - name: registration
        image: sriludone/registration:v1   # use your Docker Hub image
        ports:
        - containerPort: 5000
